# Generated by Django 5.0.7 on 2024-11-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'verbose_name': 'Попытки логина', 'verbose_name_plural': 'Попытки логинов'},
        ),
        migrations.AlterModelTable(
            name='loginattempt',
            table='loginattempt',
        ),
    ]
