# Generated by Django 5.0.7 on 2024-08-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgroup',
            name='user',
        ),
        migrations.CreateModel(
            name='UsersGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Участники', to='users.usersgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Учистник', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство пользователя в группе',
                'verbose_name_plural': 'Членства пользователей в группах',
                'db_table': 'user_group_membership',
            },
        ),
    ]
