# Generated by Django 5.0.7 on 2025-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_loginattempt_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва групи'),
        ),
    ]
