# Generated by Django 5.0.7 on 2024-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersgroup_user_usersgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroupmembership',
            name='owner_user',
            field=models.BooleanField(default=False, verbose_name='Учитель группи'),
        ),
    ]
