# Generated by Django 5.0.7 on 2025-06-05 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_question_scores_for'),
        ('users', '0005_alter_usersgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTestNotyficateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notyfies', to='tests.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
