# Generated by Django 5.0.7 on 2024-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersgroupmembership_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersgroupmembership',
            old_name='owner_user',
            new_name='owner',
        ),
    ]
