# Generated by Django 5.0.7 on 2025-06-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailtestnotyficateuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtestnotyficateuser',
            options={'verbose_name': 'Email Повідомлення по тесту', 'verbose_name_plural': 'Email Повідомлення по тестам'},
        ),
        migrations.AlterModelTable(
            name='emailtestnotyficateuser',
            table='notify_email_test',
        ),
    ]
