# Generated by Django 5.0.7 on 2025-06-21 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_question_scores'),
        ('users', '0007_alter_emailtestnotyficateuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtestnotyficateuser',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notyfies', to='tests.tests', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='emailtestnotyficateuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifyes', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
