# Generated by Django 5.0.7 on 2025-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_emailtestnotyficateuser_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва группи')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'db_table': 'group',
            },
        ),
        migrations.RemoveField(
            model_name='usersgroupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usersgroupmembership',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='members', to='users.group', verbose_name='Користувачі'),
        ),
        migrations.DeleteModel(
            name='UsersGroup',
        ),
        migrations.DeleteModel(
            name='UsersGroupMembership',
        ),
    ]
