# Generated by Django 5.0.7 on 2025-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_group_remove_usersgroupmembership_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='users.group', verbose_name='Користувачі'),
        ),
    ]
