# Generated by Django 5.2.4 on 2025-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_group_members_alter_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демо користувач'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Вчитель'),
        ),
    ]
