version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: Tests
      POSTGRES_USER: tests
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile-Local
    environment:
      ENABLE_REDIS: True
      ENABLE_CELERY: True
      DATABASE_HOST: db
      DATABASE_URL: postgres://tests:root@db:5432/Tests
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/application 
      - ./media:/application/static/media
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  celery:
    build: .
    command: celery -A main worker --loglevel=info -P solo
    # valumes:
    #   - .:/application
    depends_on:
      - redis
      - db
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgres://tests:root@db:5432/Tests
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data: