version: '3.9'
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: Tests
      POSTGRES_USER: tests
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    env_file:
      - .env
    build: 
      context: .
      # dockerfile: Dockerfile-Local
    environment:
      DATABASE_HOST: db
      DATABASE_URL: postgres://tests:root@db:5432/Tests
    volumes:
      - .:/application 
      - ./media:/application/static/media
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: