# Используем официальный Python-образ
FROM python:3.11-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /application

# Копируем файл зависимостей в контейнер и устанавливаем их
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы проекта в контейнер
COPY . /application

# Устанавливаем переменные окружения
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=main.settings
ENV DATABASE_URL=postgres://tests:root@db:5432/Tests
ENV SECURE_SSL_REDIRECT=False
ENV SESSION_COOKIE_SECURE=False
ENV CSRF_COOKIE_SECURE=False
ENV SECURE_PROXY_SSL_HEADER=None

# Открываем порт, на котором будет работать Django-сервер
EXPOSE 8000

# Запускаем скрипт ожидания и сервер Django
CMD ["sh", "-c", "python wait_for_db.py db 5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
# CMD ["gunicorn", "main.wsgi:application", "--bind", "0.0.0.0:8000"]