"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys

import dj_database_url
from django.conf.global_settings import AUTH_USER_MODEL
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# недействительный ключ

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "app",
    "tests",
    "users",
    'csp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "csp.middleware.CSPMiddleware",
    'tests.middlewares.TestExitMiddleware',
    "app.middleware.coop_policy_middleware",
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
        "default": dj_database_url.config(
            default="postgres://test:root@localhost:5432/Tests", conn_max_age=600
        )
    }

    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'Tests',
    #     'USER': 'test',
    #     'PASSWORD': 'root',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'


# Дополнительные настройки для WhiteNoise
if 'test' in sys.argv:
    # Используем стандартное хранилище для тестов, чтобы избежать ошибок с манифестом
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# STATIC_URL = 'static/'

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     BASE_DIR / "app/static",
#     BASE_DIR / "tests/static",
    
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'static' , 'media')

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/user/login/'

LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'users.backends.EmailBackend',
    # 'django.contrib.auth.backends.ModelBackend'
)

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Для тестирования

# Включаем поддержку отправки писем в Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST')  # Пример для Gmail
EMAIL_PORT = config('EMAIL_PORT', cast=int) # Используем порт для TLS

# Данные для авторизации
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# Безопасное соединение
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)  # Используется чаще всего
# EMAIL_USE_SSL = True # Для некоторых серверов можно вместо TLS

# Указываем «с обратным адресом» для всех писем
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'DEFAULT_SECRET_KEY')

# Если запускается на локальном сервере просто закоментировать
ALLOWED_HOSTS  = ['localhost', '127.0.0.1', 'yourdomain.com']

# SSL (для безопасности данных)
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://teststep-54d2adad5311.herokuapp.com", "127.0.0.1")
CSP_STYLE_SRC = ("'self'", "https://teststep-54d2adad5311.herokuapp.com", "127.0.0.1")
CSP_IMG_SRC = ("'self'", "data:", "https://teststep-54d2adad5311.herokuapp.com", "127.0.0.1")
CSP_FONT_SRC = ("'self'", "https://teststep-54d2adad5311.herokuapp.com", "127.0.0.1")
CSP_CONNECT_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)
CSP_FRAME_SRC = ("'none'",)
CSP_REPORT_ONLY = True  # Включаем режим отчёта
CSP_REPORT_URI = "/csp-report/"  # Эндпоинт для отчётов


if DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None

# SECURE_REFERRER_POLICY = 'no-referrer'

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760