# Generated by Django 5.0.7 on 2024-11-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('TXT', 'Тест з текстом'), ('IMG', 'Тест з фотографіею'), ('AUD', 'Тест з голосовим питанням'), ('MTCH', 'Тест з встановленням відповідності')], max_length=55, verbose_name='Тип питання')),
                ('answer_type', models.CharField(blank=True, choices=[('MC', 'Множинний вибір'), ('SC', 'Одиночний вибір'), ('INP', 'Текстова відповідь'), ('AUD', 'Голосова відповідь')], null=True, verbose_name='Тип відповіді')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Картинка')),
                ('audio', models.FileField(blank=True, null=True, upload_to='questions/audios/', verbose_name='Аудио')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Назва группи')),
            ],
            options={
                'verbose_name': 'Группа для вопросов',
                'verbose_name_plural': 'Группы для вопросовё',
                'db_table': 'question_group',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('max_attempts', models.PositiveIntegerField(default=2)),
                ('extra_attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.JSONField(default=list, verbose_name='Юзеры')),
                ('name', models.CharField(max_length=130, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность теста')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('date_out', models.DateTimeField(verbose_name='Будет доступный до')),
                ('check_type', models.CharField(choices=[('manual', 'Manual Check'), ('auto', 'Auto Check')], default='auto', max_length=10, verbose_name='Тип проверки ответов')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('answers', models.JSONField()),
                ('audio_answers', models.JSONField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тест на проверку',
                'verbose_name_plural': 'Тесты на проверку',
                'db_table': 'test_reviews',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=255, verbose_name='Левая часть')),
                ('right_item', models.CharField(max_length=255, verbose_name='Правая часть')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='tests.question')),
            ],
            options={
                'verbose_name': 'Пара для соответствия',
                'verbose_name_plural': 'Пари для соответствий',
                'db_table': 'matching_pairs',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('audio_response', models.FileField(blank=True, null=True, upload_to='answers/audios/', verbose_name='Голосовой ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_group', to='tests.questiongroup', verbose_name='Группа'),
        ),
    ]
