# Generated by Django 5.0.7 on 2024-11-15 13:31

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
