# Generated by Django 5.0.7 on 2024-12-23 16:44

import tests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='questions/audios/', validators=[tests.validators.validate_audio_file], verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', validators=[tests.validators.validate_image], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='check_type',
            field=models.CharField(choices=[('manual', 'Ручна перевірка'), ('auto', 'Авто-перевірка')], default='auto', max_length=10, verbose_name='Тип проверки ответов'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[tests.validators.validate_image], verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=130, unique=True, verbose_name="Ім'ям"),
        ),
    ]
