# Generated by Django 5.0.7 on 2024-10-02 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('IMG', 'Image'), ('AUD', 'Audio'), ('MTCH', 'Matching'), ('INP', 'input')], max_length=5, verbose_name='Тип вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Картинка')),
                ('audio', models.FileField(blank=True, null=True, upload_to='questions/audios/', verbose_name='Аудио')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Назва группи')),
            ],
            options={
                'verbose_name': 'Группа для вопросов',
                'verbose_name_plural': 'Группы для вопросовё',
                'db_table': 'question_group',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорію', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=255, verbose_name='Левая часть')),
                ('right_item', models.CharField(max_length=255, verbose_name='Правая часть')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='tests.question')),
            ],
            options={
                'verbose_name': 'Пара для соответствия',
                'verbose_name_plural': 'Пари для соответствий',
                'db_table': 'matching_pairs',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('audio_response', models.FileField(blank=True, null=True, upload_to='answers/audios/', verbose_name='Голосовой ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_group', to='tests.questiongroup', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.JSONField(default=list, verbose_name='Юзеры')),
                ('name', models.CharField(max_length=130, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность теста')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('date_out', models.DateTimeField(verbose_name='Будет доступный до')),
                ('check_type', models.CharField(choices=[('manual', 'Manual Check'), ('auto', 'Auto Check')], default='auto', max_length=10, verbose_name='Тип проверки ответов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.categories', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('max_attempts', models.PositiveIntegerField(default=2)),
                ('extra_attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'db_table': 'test_results',
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.tests', verbose_name='Тест', default=1),
        ),
        migrations.CreateModel(
            name='TestsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField()),
                ('audio_answers', models.JSONField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tests.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест на проверку',
                'verbose_name_plural': 'Тесты на проверку',
                'db_table': 'test_reviews',
            },
        ),
    ]
