# Generated by Django 5.0.7 on 2025-01-20 17:45

import tests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_audio_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test-images', validators=[tests.validators.validate_image], verbose_name='Превью'),
        ),
    ]
