# Generated by Django 5.0.7 on 2024-07-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_tests_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
