# Generated by Django 5.0.7 on 2025-02-08 18:11

import django.db.models.deletion
import tests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_tests_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='matchingpair',
            options={'verbose_name': 'Пара для відповідності', 'verbose_name_plural': 'Пари для відповідності'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'verbose_name': 'Группа для питань', 'verbose_name_plural': 'Группы для питань'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результати тестів'},
        ),
        migrations.AlterModelOptions(
            name='testsreviews',
            options={'verbose_name': 'Тест на перевірку', 'verbose_name_plural': 'Тесты на перевірку'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='answers/audios/', verbose_name='Голосова відповідь'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст відповіді'),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='left_item',
            field=models.CharField(max_length=255, verbose_name='Ліва частина'),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_item',
            field=models.CharField(max_length=255, verbose_name='Права частина'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', validators=[tests.validators.validate_image], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст питання'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.categories', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='check_type',
            field=models.CharField(choices=[('manual', 'Ручна перевірка'), ('auto', 'Авто-перевірка')], default='auto', max_length=10, verbose_name='Тип перевірки відповідей'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='date_out',
            field=models.DateTimeField(verbose_name='Буде доступний до'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продовжуваність теста'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=130, unique=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='tests',
            name='students',
            field=models.JSONField(default=list, verbose_name='Студенти'),
        ),
    ]
