# Generated by Django 5.0.7 on 2024-10-19 13:32

import django.utils.timezone
from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='duration',
            field=models.DurationField(default=timedelta),
            preserve_default=False,
        ),
    ]
