# Generated by Django 5.0.7 on 2025-05-28 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_answer_options_alter_matchingpair_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsreviews',
            options={'verbose_name': 'Тест на перевірку', 'verbose_name_plural': 'Тести на перевірку'},
        ),
        migrations.AddField(
            model_name='tests',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 16, 6, 18, 231150, tzinfo=datetime.timezone.utc), verbose_name='c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests',
            name='date_out',
            field=models.DateTimeField(verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='students',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Студенти'),
        ),
    ]
