# Generated by Django 5.0.7 on 2024-08-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_tests_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продолжительность теста'),
        ),
    ]
