# Generated by Django 5.0.7 on 2024-10-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testresult_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
