# Generated by Django 5.0.7 on 2025-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_testsreviews_options_tests_date_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Бали за відповідь'),
        ),
        migrations.AddField(
            model_name='matchingpair',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Бали за відповідність'),
        ),
        migrations.AddField(
            model_name='question',
            name='scores',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Бали за питання'),
        ),
    ]
