# Generated by Django 5.0.7 on 2024-10-23 11:41

from django.db import migrations, models
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_testresult_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsreviews',
            name='duration',
            field=models.DurationField(default=timedelta),
            preserve_default=False,
        ),
    ]
