# Generated by Django 5.0.7 on 2024-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_tests_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=130, unique=True, verbose_name='Название'),
        ),
    ]
