# Generated by Django 5.0.7 on 2024-08-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_tests_description_alter_tests_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.categories', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
