# Generated by Django 5.0.7 on 2024-10-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_testsreviews_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
    ]
