# Generated by Django 5.0.7 on 2024-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('INP', 'Текстова відповідь'), ('AUD', 'Голосова відповідь')], default=1, verbose_name='Тип відповіді'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Одиночний вибір'), ('MC', 'Множинний вибір'), ('IMG', 'Тест з фотографіею'), ('AUD', 'Тест з голосовим питанням'), ('MTCH', 'Встановлення відповідності'), ('INP', 'input')], max_length=55, verbose_name='Тип питання'),
        ),
    ]
