# Generated by Django 5.0.7 on 2024-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_tests_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='duration',
            field=models.DurationField(blank=True, default=60, null=True, verbose_name='Продолжительность теста'),
        ),
    ]
