# Generated by Django 5.0.7 on 2025-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_answer_score_alter_matchingpair_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scores_for',
            field=models.CharField(blank=True, choices=[('SA', 'Баллы за відповідь'), ('SQ', 'Баллы за питання')], null=True, verbose_name='Тип оцінювання'),
        ),
    ]
