# Generated by Django 5.0.7 on 2025-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_question_scores_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Бали за відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scores',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Бали за питання'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scores_for',
            field=models.CharField(blank=True, choices=[('SA', 'Бали за відповідь'), ('SQ', 'Бали за питання')], null=True, verbose_name='Тип оцінювання'),
        ),
    ]
