# Generated by Django 5.0.7 on 2024-10-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_question_answer_type_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('INP', 'Текстова відповідь'), ('AUD', 'Голосова відповідь')], null=True, verbose_name='Тип відповіді'),
        ),
    ]
