# Generated by Django 5.0.7 on 2024-08-13 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_tests_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
