# Generated by Django 5.0.7 on 2024-11-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_question_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('MC', 'Множинний вибір'), ('SC', 'Одиночний вибір'), ('INP', 'Текстова відповідь'), ('AUD', 'Голосова відповідь')], null=True, verbose_name='Тип відповіді'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TXT', 'Тест з текстом'), ('IMG', 'Тест з фотографіею'), ('AUD', 'Тест з голосовим питанням'), ('MTCH', 'Тест з встановленням відповідності')], max_length=55, verbose_name='Тип питання'),
        ),
    ]
