# Generated by Django 5.0.7 on 2025-06-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_answer_score_alter_question_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scores_for',
            field=models.CharField(choices=[('SA', 'Бали за відповідь'), ('SQ', 'Бали за питання')], default='SA', verbose_name='Тип оцінювання'),
            preserve_default=False,
        ),
    ]
