# Generated by Django 5.0.7 on 2025-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_question_scores_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scores',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Бали за питання'),
        ),
    ]
