# Generated by Django 5.0.7 on 2024-08-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_tests_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default='single', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.tests', verbose_name='Тест'),
        ),
    ]
