# Generated by Django 5.0.7 on 2024-11-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
        ('tests', '0010_alter_question_answer_type_and_more'),
    ]

    operations = [
    ]
