# Generated by Django 5.0.7 on 2025-06-26 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_answer_score_alter_matchingpair_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='students',
        ),
        migrations.AddField(
            model_name='tests',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
