# Generated by Django 5.0.7 on 2025-06-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_remove_tests_students_tests_students'),
        ('users', '0012_group_members_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_group', to='users.group'),
            preserve_default=False,
        ),
    ]
