# Generated by Django 5.0.7 on 2024-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_tests_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('IMG', 'Image'), ('AUD', 'Audio'), ('MTCH', 'Matching'), ('TXT', 'Text')], max_length=5, verbose_name='Тип вопроса'),
        ),
    ]
