# Generated by Django 5.0.7 on 2025-06-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_tests_group'),
        ('users', '0012_group_members_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsreviews',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='testsreviews',
            name='score',
        ),
        migrations.AlterField(
            model_name='testsreviews',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_reviews', to='users.group'),
        ),
    ]
