# Generated by Django 5.0.7 on 2025-06-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_remove_testsreviews_reviewed_and_more'),
        ('users', '0012_group_members_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsreviews',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_reviews', to='users.group'),
        ),
    ]
