# Generated by Django 5.0.7 on 2025-06-27 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_alter_testsreviews_group'),
        ('users', '0012_group_members_alter_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='users.group'),
        ),
        migrations.AlterField(
            model_name='testsreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
