# Generated by Django 5.0.7 on 2024-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_remove_answer_matching_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testresult',
            name='extra_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='max_attempts',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
