# Generated by Django 5.0.7 on 2024-08-25 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_testresult_attempts_testresult_extra_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='check_type',
            field=models.CharField(choices=[('manual', 'Manual Check'), ('auto', 'Auto Check')], default='auto', max_length=10, verbose_name='Тип проверки ответов'),
        ),
        migrations.CreateModel(
            name='TestsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tests.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
