# Generated by Django 5.0.7 on 2024-09-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_tests_check_type_testsreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsreviews',
            options={'verbose_name': 'Тест на проверку', 'verbose_name_plural': 'Тесты на проверку'},
        ),
        migrations.AlterModelTable(
            name='testsreviews',
            table='test_reviews',
        ),
    ]
