# Generated by Django 5.0.7 on 2024-09-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_alter_testsreviews_options_alter_testsreviews_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Назва группи')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests')),
            ],
            options={
                'verbose_name': 'Группа для вопросов',
                'verbose_name_plural': 'Группы для вопросовё',
                'db_table': 'question_group',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_group', to='tests.questiongroup', verbose_name='Группа'),
        ),
    ]
