# Generated by Django 5.0.7 on 2024-09-04 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_questiongroup_question_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsreviews',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
