# Generated by Django 5.0.7 on 2024-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_testsreviews_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='answers/audios/', verbose_name='Голосовой ответ'),
        ),
    ]
