# Generated by Django 5.0.7 on 2024-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_answer_audio_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsreviews',
            name='audio_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
