# Generated by Django 5.0.7 on 2024-09-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_testsreviews_audio_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('IMG', 'Image'), ('AUD', 'Audio'), ('MTCH', 'Matching'), ('INP', 'input')], max_length=5, verbose_name='Тип вопроса'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=255, verbose_name='Левая часть')),
                ('right_item', models.CharField(max_length=255, verbose_name='Правая часть')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mathcing_pairs', to='tests.question')),
            ],
            options={
                'verbose_name': 'Пара для соответствия',
                'verbose_name_plural': 'Пари для соответствий',
                'db_table': 'matching_pairs',
            },
        ),
    ]
