# Generated by Django 5.0.7 on 2024-09-27 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_alter_question_question_type_matchingpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='date_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tests',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='tests.question'),
        ),
    ]
